import { api } from "tina4js";

// Represents a single item included on an invoice.
export interface InvoiceItem {
	id: number;
	product_id: number;
	product_name: string;
	price: number;
	quantity: number;
}

// Represents an invoice generated by checkout.
export interface Invoice {
	id: number;
	user_id: number;
	cart_id: number;
	total: number;
	status: string;
	items: InvoiceItem[];
}

// Represents the response returned after successfully completing checkout.
export interface CheckoutResponse {
	message: string;
	invoice: Invoice;
}

// Complete the checkout process.
export async function checkout(): Promise<CheckoutResponse> {
	/* 
		Send a POST request to the checkout endpoint. 
		
		The backend uses the current user's cart to 
		generate the invoice.
	*/
	return (await api.post("/checkout")) as CheckoutResponse;
}
